package bus_test

import (
	"context"
	"log/slog"
	"os"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/axiom-ide/axiom/api"
	"github.com/axiom-ide/axiom/core/bus"
)

var testLogger = slog.New(slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelError}))

func newBus(t *testing.T) (*bus.EventBus, context.CancelFunc) {
	t.Helper()
	ctx, cancel := context.WithCancel(context.Background())
	t.Cleanup(cancel)
	return bus.New(ctx, 64, testLogger), cancel
}

func TestPublishReceived(t *testing.T) {
	eb, _ := newBus(t)
	received := make(chan api.Event, 1)
	eb.Subscribe(api.TopicFileRead, func(ev api.Event) {
		received <- ev
	})
	eb.Publish(api.Event{Topic: api.TopicFileRead, Source: "test"})
	select {
	case ev := <-received:
		if ev.Source != "test" {
			t.Errorf("expected source 'test', got '%s'", ev.Source)
		}
	case <-time.After(500 * time.Millisecond):
		t.Fatal("event not received within timeout")
	}
}

func TestPublishSyncBlocks(t *testing.T) {
	eb, _ := newBus(t)
	var count int32
	eb.Subscribe(api.TopicSystemReady, func(_ api.Event) {
		time.Sleep(10 * time.Millisecond)
		atomic.AddInt32(&count, 1)
	})
	eb.Subscribe(api.TopicSystemReady, func(_ api.Event) {
		time.Sleep(10 * time.Millisecond)
		atomic.AddInt32(&count, 1)
	})
	eb.PublishSync(api.Event{Topic: api.TopicSystemReady, Source: "engine"})
	if atomic.LoadInt32(&count) != 2 {
		t.Errorf("PublishSync should wait for all handlers, count=%d", count)
	}
}

func TestUnsubscribe(t *testing.T) {
	eb, _ := newBus(t)
	var count int32
	subID := eb.Subscribe(api.TopicFileRead, func(_ api.Event) {
		atomic.AddInt32(&count, 1)
	})
	eb.Unsubscribe(api.TopicFileRead, subID)
	eb.PublishSync(api.Event{Topic: api.TopicFileRead})
	time.Sleep(50 * time.Millisecond)
	if atomic.LoadInt32(&count) != 0 {
		t.Errorf("handler should not be called after Unsubscribe, count=%d", count)
	}
}

func TestMultipleSubscribers(t *testing.T) {
	eb, _ := newBus(t)
	var wg sync.WaitGroup
	wg.Add(3)
	for i := 0; i < 3; i++ {
		eb.Subscribe(api.TopicFileWrite, func(_ api.Event) {
			wg.Done()
		})
	}
	eb.Publish(api.Event{Topic: api.TopicFileWrite})
	done := make(chan struct{})
	go func() { wg.Wait(); close(done) }()
	select {
	case <-done:
	case <-time.After(500 * time.Millisecond):
		t.Fatal("not all subscribers were called")
	}
}

func TestNoSubscribersNoError(t *testing.T) {
	eb, _ := newBus(t)
	// Publier sur un topic sans abonnés ne doit pas paniquer
	eb.Publish(api.Event{Topic: "topic.with.nobody", Source: "test"})
}

func TestPanicInHandlerDoesNotKillBus(t *testing.T) {
	eb, _ := newBus(t)
	received := make(chan struct{}, 1)

	// Handler qui panique
	eb.Subscribe(api.TopicFileRead, func(_ api.Event) {
		panic("intentional panic in test handler")
	})
	// Deuxième handler sur le même topic — doit quand même recevoir
	eb.Subscribe(api.TopicFileRead, func(_ api.Event) {
		received <- struct{}{}
	})

	eb.Publish(api.Event{Topic: api.TopicFileRead})

	select {
	case <-received:
		// OK — le bus a survécu à la panique
	case <-time.After(500 * time.Millisecond):
		t.Fatal("bus did not survive handler panic")
	}
}

func TestShutdownIdempotent(t *testing.T) {
	// Annuler le contexte deux fois ne doit pas paniquer (double-close)
	ctx, cancel := context.WithCancel(context.Background())
	eb := bus.New(ctx, 64, testLogger)
	eb.Subscribe(api.TopicSystemReady, func(_ api.Event) {})
	cancel() // premier shutdown
	cancel() // deuxième — ne doit pas paniquer
	time.Sleep(50 * time.Millisecond)
}

func TestEventIDAutoGenerated(t *testing.T) {
	eb, _ := newBus(t)
	received := make(chan api.Event, 1)
	eb.Subscribe(api.TopicFileCreate, func(ev api.Event) {
		received <- ev
	})
	// Publier sans ID
	eb.Publish(api.Event{Topic: api.TopicFileCreate, Source: "test"})
	select {
	case ev := <-received:
		if ev.ID == "" {
			t.Error("event ID should be auto-generated")
		}
	case <-time.After(500 * time.Millisecond):
		t.Fatal("event not received")
	}
}