// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {filesystem} from '../models';

export function CreateFile(arg1:string,arg2:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function EmitEvent(arg1:string,arg2:string):Promise<void>;

export function GetConfig():Promise<Record<string, any>>;

export function ListDir(arg1:string):Promise<Array<filesystem.FileEntry>>;

export function OpenTab(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveWorkspace():Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
